
CREATE TABLE "USUARIOS" (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USUARIO TEXT,
    ID_USUARIO TEXT  UNIQUE,
    NFC TEXT,
    RFID TEXT
);

CREATE TABLE "SALDO" (
    ID_USUARIO TEXT PRIMARY KEY,
    DINERO INTEGER,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS ( ID_USUARIO )
);

CREATE TABLE "PASSWORD" (
    ID_USUARIO TEXT PRIMARY KEY,
    CONTRASEÑA TEXT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS ( ID_USUARIO )
);

CREATE TABLE "RECARGA"(
    ID_USUARIO TEXT,
    DIA INTEGER,
    MES INTEGER,
    YEAR INTEGER,
    SEGUNDO INTEGER,
    MINUTO INTEGER, 
    HORA INTEGER,
    MONTO INTEGER,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE TABLE "VENDEDOR"(
    USUARIO TEXT PRIMARY KEY,
    PASSWORD TEXT
);

DELETE from PASSWORD;
DELETE from SALDO;
DELETE from PASSWORD;
DELETE from USUARIOS;

SELECT MAX(ID_USUARIO) AS last_id FROM USUARIOS;

DROP TABLE PASSWORD;
DROP TABLE FONDO;
DROP TABLE USUARIOS;


SELECT U.USUARIO, S.DINERO, U.ID_USUARIO, P.CONTRASEÑA
FROM  USUARIOS U, PASSWORD P, SALDO S
WHERE U.ID_USUARIO LIKE "%10000%"
AND S.ID_USUARIO LIKE "%10000%"
AND P.ID_USUARIO LIKE "%10000%";


DELETE FROM SALDO;
DELETE FROM RECARGA;
DELETE FROM PASSWORD;
DELETE FROM USUARIOS;
DELETE FROM sqlite_sequence;
